vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        image_regime:
            uri_prefix: /images/regime
            upload_destination: '%kernel.project_dir%/public/images/regime'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
